version: "3.9"

services:
  telegram-bot:
    build:
      context: .
    container_name: telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: python bot.py
